name: Publish Docker Image

on:
  push:
    branches:
      - main
      - docker-dev

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Schritt zum Erstellen der .npmrc
      - name: Setup .npmrc
        run: |
          echo "@jimce-music:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          # Zusätzlich für alle Fälle die globale Registry setzen:
          echo "registry=https://registry.npmjs.org/" >> .npmrc

      - name: Login GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (docker-dev)
        if: github.ref == 'refs/heads/docker-dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          secrets: |
            npmrc=./.npmrc

      - name: Build & Push (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jimce-music/jimce-webclient:latest
            ghcr.io/jimce-music/jimce-webclient:${{ github.sha }}
          secrets: |
            npmrc_token=${{ secrets.NPM_TOKEN }}